name: simple_app_cache_manager
description: Flutter Package for Managing Application Cache
version: 0.0.4
homepage: https://github.com/therasuldev/simple_app_cache_manager

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.simple_app_cache_manager
        pluginClass: SimpleAppCacheManagerPlugin
      ios:
        pluginClass: SimpleAppCacheManagerPlugin